---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hetzner-keepalived
  namespace: keepalived
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hetzner-keepalived
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hetzner-keepalived
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hetzner-keepalived
subjects:
- kind: ServiceAccount
  name: hetzner-keepalived
  namespace: keepalived
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hetzner-keepalived
  namespace: keepalived
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hetzner-keepalived
    spec:
      hostNetwork: true
      serviceAccount: hetzner-keepalived
      containers:
      - name: hetzner-keepalived
        image: yoshz/hetzner-keepalived
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - mountPath: /dev
          name: dev
        env:
        - name: HETZNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: hetzner
              key: token
        - name: IFACE
          valueFrom:
            configMapKeyRef:
              name: keepalived
              key: iface
        - name: VIPS
          valueFrom:
            configMapKeyRef:
              name: keepalived
              key: vips
      volumes:
      - name: dev
        hostPath:
          path: /dev